name: Compilação Android via Flet

on:
  push:
    branches:
      - principal 
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código Fonte
        uses: actions/checkout@v4

      # 1. Configura o Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      # 2. Configura o ambiente Python e instala o Flet
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Instalar Flet
        run: pip install flet

      # 3. NOVO PASSO: Aceitar as licenças do Android SDK
      - name: Aceitar Licenças Android
        run: yes | flutter doctor --android-licenses

      # 4. Compila o APK (Usando a correção do --module-name)
      - name: Build Android APK
        # O 'flet build' agora terá todas as licenças aceitas
        run: flet build apk --module-name AnimalSoundsAppV2

      # 5. Upload do APK como Artefato
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_APK
          path: build/app/outputs/flutter-apk/app-release.apk
