name: Compilação Android via Flet

on:
  push:
    branches:
      - principal 
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código Fonte
        uses: actions/checkout@v4

      # 1. Configura o Flutter SDK (ambiente base para o Flet)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      # 2. Configura o ambiente Python e instala o Flet
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Flet
        run: pip install flet

      # 3. Compila o APK (CORREÇÃO APLICADA AQUI)
      - name: Build Android APK
        # Use o --module-name para especificar o seu arquivo principal (AnimalSoundsAppV2.py)
        run: flet build apk --module-name AnimalSoundsAppV2

      # 4. Upload do APK como Artefato
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_APK
          path: build/app/outputs/flutter-apk/app-release.apk
